"""Bounded durable Voice producer claims and retryable blob-cleanup journals."""

from dataclasses import dataclass
import json
from typing import TYPE_CHECKING

from metor.core.api import Delivery, is_valid_message_id
from metor.utils import Constants

if TYPE_CHECKING:
    from .manager import SqlManager


@dataclass(frozen=True)
class VoiceProducerItem:
    """Binds a single logical recording to its Core-issued owner token."""

    msg_id: str
    onion: str
    owner_token: str
    delivery: Delivery
    cleanup_payload: str | None = None
    interrupted: bool = False
    allocated_ids: tuple[str, ...] = ()


class VoiceProducerRepository:
    """Owns durable claims; connected-session authorization stays in Core."""

    def __init__(self, sql: 'SqlManager', protected: bool) -> None:
        """Binds claims to the selected profile's actual storage protection.

        Args:
            sql: Initialized profile SQL owner.
            protected: Actual keyed connection mode, never a frontend assertion.
        Returns:
            None
        """
        self._sql = sql
        self.protected = protected

    def items(self) -> tuple[VoiceProducerItem, ...]:
        """Reads the bounded cleanup inventory without exposing it to a frontend.

        Args:
            None
        Returns:
            tuple[VoiceProducerItem, ...]: Current owner claims and cleanup intents.
        """
        rows = self._sql.fetchall(
            'SELECT msg_id, peer_onion, owner_token, delivery, cleanup_payload, interrupted, allocated_ids '
            'FROM voice_producer_items ORDER BY msg_id LIMIT ?',
            (Constants.VOICE_OWNER_MAX_PROFILE_ITEMS,),
        )
        return tuple(
            VoiceProducerItem(
                str(row[0]),
                str(row[1]),
                str(row[2]),
                Delivery(str(row[3])),
                str(row[4]) if row[4] is not None else None,
                bool(row[5]),
                self._decode_allocations(str(row[6])),
            )
            for row in rows
        )

    def get(self, msg_id: str) -> VoiceProducerItem | None:
        """Looks up exact recording ownership without guessing from a peer alias.

        Args:
            msg_id: Globally admitted outbound recording ID for this runtime.
        Returns:
            VoiceProducerItem | None: Durable owner claim, if present.
        """
        rows = self._sql.fetchall(
            'SELECT msg_id, peer_onion, owner_token, delivery, cleanup_payload, interrupted, allocated_ids '
            'FROM voice_producer_items WHERE msg_id = ?',
            (msg_id,),
        )
        if not rows:
            return None
        row = rows[0]
        return VoiceProducerItem(
            str(row[0]),
            str(row[1]),
            str(row[2]),
            Delivery(str(row[3])),
            str(row[4]) if row[4] is not None else None,
            bool(row[5]),
            self._decode_allocations(str(row[6])),
        )

    @staticmethod
    def _decode_allocations(payload: str) -> tuple[str, ...]:
        """Validates the bounded pre-write allocation journal.

        Args:
            payload: Protected serialized object inventory.
        Returns:
            tuple[str, ...]: Validated opaque IDs.
        """
        if len(payload.encode('utf-8')) > Constants.VOICE_METADATA_MAX_BYTES:
            raise ValueError('Oversized Voice allocation journal')
        value = json.loads(payload)
        if (
            not isinstance(value, list)
            or len(value) > Constants.VOICE_MAX_SEGMENTS + 1
            or any(not isinstance(item, str) for item in value)
        ):
            raise ValueError('Invalid Voice allocation journal')
        return tuple(value)

    def reserve_blob(self, item: VoiceProducerItem, blob_id: str) -> None:
        """Persists ownership before an object can be created outside SQL.

        Args:
            item: Exact current recording claim.
            blob_id: Fresh opaque ID generated by the Core allocation adapter.
        Returns:
            None
        """
        payload = json.dumps([*item.allocated_ids, blob_id], separators=(',', ':'))
        self._decode_allocations(payload)
        self._sql.execute(
            'UPDATE voice_producer_items SET allocated_ids = ? WHERE msg_id = ? AND owner_token = ?',
            (payload, item.msg_id, item.owner_token),
        )

    def mark_interrupted(self, item: VoiceProducerItem) -> None:
        """Records producer loss before attempting accepted-prefix finalization.

        Args:
            item: Revoked LIVE producer claim.
        Returns:
            None
        """
        self._sql.execute(
            'UPDATE voice_producer_items SET interrupted = 1 WHERE msg_id = ? AND owner_token = ?',
            (item.msg_id, item.owner_token),
        )

    def claim(
        self, owner_token: str, onion: str, msg_id: str, delivery: Delivery
    ) -> bool:
        """Reserves durable ownership before recording admission can create bytes.

        Args:
            owner_token: Core-issued active session owner.
            onion: Canonical target resolved by Core.
            msg_id: New logical recording identity.
            delivery: Immutable initial authorization semantics.
        Returns:
            bool: Whether the bounded fresh claim was recorded.
        """
        if not self.protected:
            raise PermissionError('Protected staging is unavailable')
        if (
            not is_valid_message_id(msg_id)
            or len(owner_token) != Constants.VOICE_OWNER_TOKEN_BYTES * 2
        ):
            raise ValueError('Invalid Voice owner claim')
        with self._sql.transaction() as cursor:
            cursor.execute('SELECT COUNT(*) FROM voice_producer_items')
            total = cursor.fetchone()
            if (
                not isinstance(total, tuple)
                or int(total[0]) >= Constants.VOICE_OWNER_MAX_PROFILE_ITEMS
            ):
                return False
            cursor.execute(
                'SELECT delivery FROM voice_producer_items WHERE owner_token = ?',
                (owner_token,),
            )
            rows = cursor.fetchall()
            if len(rows) >= Constants.VOICE_OWNER_MAX_ITEMS or (
                delivery is Delivery.DROP
                and sum(row[0] == Delivery.DROP.value for row in rows)
                >= Constants.VOICE_OWNER_MAX_DRAFTS
            ):
                return False
            if delivery is Delivery.DROP:
                cursor.execute(
                    "SELECT 1 FROM voice_producer_items WHERE owner_token = ? AND peer_onion = ? AND delivery = 'drop'",
                    (owner_token, onion),
                )
                if cursor.fetchone() is not None:
                    return False
            cursor.execute(
                'SELECT 1 FROM voice_producer_items WHERE msg_id = ?', (msg_id,)
            )
            if cursor.fetchone() is not None:
                return False
            cursor.execute(
                "SELECT 1 FROM message_receipts WHERE msg_id = ? AND direction = 'out'",
                (msg_id,),
            )
            if cursor.fetchone() is not None:
                return False
            cursor.execute(
                'INSERT INTO voice_producer_items (msg_id, peer_onion, owner_token, delivery) VALUES (?, ?, ?, ?)',
                (msg_id, onion, owner_token, delivery.value),
            )
            return True

    def prepare_cleanup(self, item: VoiceProducerItem, payload: str) -> None:
        """Persists the exact blob inventory before deleting any draft receipt.

        Args:
            item: Exact owner claim being reclaimed.
            payload: Validated canonical metadata retained for retryable blob deletion.
        Returns:
            None
        """
        if len(payload.encode('utf-8')) > Constants.VOICE_METADATA_MAX_BYTES:
            raise ValueError('Voice cleanup metadata exceeds its bound')
        self._sql.execute(
            'UPDATE voice_producer_items SET cleanup_payload = ? WHERE msg_id = ? AND owner_token = ?',
            (payload, item.msg_id, item.owner_token),
        )

    def release(self, item: VoiceProducerItem) -> None:
        """Releases only a reconciled exact claim after commit or completed cleanup.

        Args:
            item: Claim whose lifecycle transfer or reclamation is complete.
        Returns:
            None
        """
        self._sql.execute(
            'DELETE FROM voice_producer_items WHERE msg_id = ? AND owner_token = ?',
            (item.msg_id, item.owner_token),
        )
