"""
Package initializer for the IPC API layer.
Exposes the fully decoupled Domain Transfer Objects (DTOs) and Enums through a unified Facade.
Guarantees strict backward compatibility for all internal application imports.
"""

from metor.core.api.codes import Action, EventType, TransCode
from metor.core.api.base import IpcMessage, IpcCommand, IpcEvent
from metor.core.api.commands import (
    InitCommand,
    GetConnectionsCommand,
    GetContactsListCommand,
    ConnectCommand,
    DisconnectCommand,
    AcceptCommand,
    RejectCommand,
    MsgCommand,
    AddContactCommand,
    RemoveContactCommand,
    RenameContactCommand,
    ClearContactsCommand,
    SwitchCommand,
    SendDropCommand,
    GetInboxCommand,
    MarkReadCommand,
    FallbackCommand,
    GetHistoryCommand,
    ClearHistoryCommand,
    GetMessagesCommand,
    ClearMessagesCommand,
    GetAddressCommand,
    GenerateAddressCommand,
    ClearProfileDbCommand,
    SetSettingCommand,
    SelfDestructCommand,
    UnlockCommand,
)
from metor.core.api.events import (
    InitEvent,
    RemoteMsgEvent,
    AckEvent,
    ConnectedEvent,
    DisconnectedEvent,
    RenameSuccessEvent,
    ContactRemovedEvent,
    ConnectionsStateEvent,
    SwitchSuccessEvent,
    ConnectionPendingEvent,
    ConnectionAutoAcceptedEvent,
    ConnectionRetryEvent,
    ConnectionFailedEvent,
    IncomingConnectionEvent,
    ConnectionRejectedEvent,
    InboxNotificationEvent,
    InboxDataEvent,
    MsgFallbackToDropEvent,
    NotificationEvent,
    CommandResponseEvent,
)


__all__ = [
    'Action',
    'EventType',
    'TransCode',
    'IpcMessage',
    'IpcCommand',
    'IpcEvent',
    'InitCommand',
    'GetConnectionsCommand',
    'GetContactsListCommand',
    'ConnectCommand',
    'DisconnectCommand',
    'AcceptCommand',
    'RejectCommand',
    'MsgCommand',
    'AddContactCommand',
    'RemoveContactCommand',
    'RenameContactCommand',
    'ClearContactsCommand',
    'SwitchCommand',
    'SendDropCommand',
    'GetInboxCommand',
    'MarkReadCommand',
    'FallbackCommand',
    'GetHistoryCommand',
    'ClearHistoryCommand',
    'GetMessagesCommand',
    'ClearMessagesCommand',
    'GetAddressCommand',
    'GenerateAddressCommand',
    'ClearProfileDbCommand',
    'SetSettingCommand',
    'SelfDestructCommand',
    'UnlockCommand',
    'InitEvent',
    'RemoteMsgEvent',
    'AckEvent',
    'ConnectedEvent',
    'DisconnectedEvent',
    'RenameSuccessEvent',
    'ContactRemovedEvent',
    'ConnectionsStateEvent',
    'SwitchSuccessEvent',
    'ConnectionPendingEvent',
    'ConnectionAutoAcceptedEvent',
    'ConnectionRetryEvent',
    'ConnectionFailedEvent',
    'IncomingConnectionEvent',
    'ConnectionRejectedEvent',
    'InboxNotificationEvent',
    'InboxDataEvent',
    'MsgFallbackToDropEvent',
    'NotificationEvent',
    'CommandResponseEvent',
]
